# Generated by Django 5.0.3 on 2024-03-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_doctor_staff_medicalrecord_patient_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_leave', 'On Leave')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_info',
            field=models.CharField(max_length=10),
        ),
    ]
