# Generated by Django 5.0.3 on 2024-03-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_alter_doctor_availability_alter_doctor_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
