# Generated by Django 5.0.3 on 2024-03-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_alter_medicalrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctor'),
        ),
    ]
