# Generated by Django 5.0.3 on 2024-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_alter_staff_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_leave', 'On Leave')], default='available', max_length=20),
        ),
    ]
