# Generated by Django 5.0.3 on 2024-03-23 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0009_medicalinventoryitem_medicalinventoryexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity_used', models.IntegerField(default=0)),
                ('notes_usage', models.TextField(blank=True)),
                ('date_incurred', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes_expense', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalinventoryusage',
            name='item',
        ),
        migrations.DeleteModel(
            name='MedicalInventoryExpense',
        ),
        migrations.DeleteModel(
            name='MedicalInventoryItem',
        ),
        migrations.DeleteModel(
            name='MedicalInventoryUsage',
        ),
    ]
