# Generated by Django 5.0.3 on 2024-03-25 04:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0010_medicalinventoryrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triage_level', models.CharField(choices=[('1', 'Immediate'), ('2', 'Delayed'), ('3', 'Minimal'), ('4', 'Expectant')], max_length=1)),
                ('triage_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.emergency')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.patient')),
            ],
        ),
    ]
