# Generated by Django 5.0.3 on 2024-03-26 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0011_emergency_triage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='emergency',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='patient',
        ),
        migrations.AddField(
            model_name='emergency',
            name='patient_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='triage_level',
            field=models.CharField(choices=[('1', 'Immediate'), ('2', 'Delayed'), ('3', 'Minimal'), ('4', 'Expectant')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Patient_Appointment',
        ),
        migrations.DeleteModel(
            name='Triage',
        ),
    ]
