# Generated by Django 5.0.3 on 2024-03-26 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0013_remove_emergency_patient_name_appointment_emergency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_app.doctor'),
        ),
    ]
