# Generated by Django 5.0.3 on 2024-03-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0014_appointment_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='emergency',
        ),
    ]
