# Generated by Django 5.0.3 on 2024-03-27 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0017_alter_appointment_assigned_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='name',
            new_name='accident',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.emergency'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hospital_app.staff'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('reception', 'Receptionist'), ('cleaner', 'Cleaner')], default='reception', max_length=20),
        ),
    ]
