# Generated by Django 5.0.3 on 2024-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0019_emergency_patient_name_alter_patient_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20),
        ),
    ]
