# Generated by Django 5.0.3 on 2024-04-08 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0021_remove_staff_name_remove_staff_role_user_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact_info',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact_information', message='Contact information must be a 10-digit number.', regex='^[0-9]{10}$')]),
        ),
    ]
