# Generated by Django 5.0.3 on 2024-04-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0022_alter_staff_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital_app.user'),
            preserve_default=False,
        ),
    ]
