# Generated by Django 5.0.3 on 2024-04-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0024_alter_schedule_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
