# Generated by Django 5.0.3 on 2024-04-18 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0026_doctor_remove_user_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital_app.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
