# Generated by Django 5.0.3 on 2024-04-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0027_alter_appointment_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor',
            new_name='name',
        ),
    ]
